name: minesweeper 
description: minesweeper.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  change_app_package_name: ^1.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/typeface/
    - assets/icons/
    - assets/videos/
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/typeface/Lexend/Lexend-Black.ttf
          weight: 900
        - asset: assets/typeface/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/typeface/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/typeface/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/typeface/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/typeface/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/typeface/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/typeface/Lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/typeface/Lexend/Lexend-Thin.ttf
          weight: 100
    - family: Inter
      fonts:
        - asset: assets/typeface/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/typeface/Inter/Inter-Extrabold.ttf
          weight: 800
        - asset: assets/typeface/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/typeface/Inter/Inter-Semibold.ttf
          weight: 600
        - asset: assets/typeface/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/typeface/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/typeface/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/typeface/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/typeface/Inter/Inter-Thin.ttf
          weight: 100
